export const API_STATUS = {
    SUCCESS: 200,
    TWO_ZERO_ONE: 201,
    TWO_ZERO_TWO: 202,
    FOUR_ZERO_ZERO: 400,
    FOUR_ZERO_ONE: 401,
    FOUR_ZERO_TWO: 402,
    FOUR_ZERO_THREE: 403,
    FOUR_ZERO_FIVE: 405,
};

export const NUMBER_CONST = {
    MINUS_ONE: -1,
    ZERO: 0,
    ONE: 1,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    FIVE: 5,
    SIX: 6,
    SEVEN: 7,
    EIGHT: 8,
    NINE:9,
    TEN: 10,
    ELEVEN:11,
    TWELVE:12,
    THIRTEEN:13,
    FOURTEEN:14,
    THIRTY_TWO: 32,
    FOURTY_THREE:43,
    TYPE_ONE:1,
    TYPE_TWO:2,
    TYPE_THREE:3,
}